/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as StudentAttendanceRouteImport } from './routes/student-attendance'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TodayAttendanceRouteImport } from './routes/today-attendance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/student-attendance',
  path: '/student-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayAttendanceRoute = TodayAttendanceRouteImport.update({
  id: '/today-attendance',
  path: '/today-attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/performance': typeof PerformanceRoute
  '/student-attendance': typeof StudentAttendanceRoute
  '/timetable': typeof TimetableRoute
  '/today-attendance': typeof TodayAttendanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/performance': typeof PerformanceRoute
  '/student-attendance': typeof StudentAttendanceRoute
  '/timetable': typeof TimetableRoute
  '/today-attendance': typeof TodayAttendanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/performance': typeof PerformanceRoute
  '/student-attendance': typeof StudentAttendanceRoute
  '/timetable': typeof TimetableRoute
  '/today-attendance': typeof TodayAttendanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/performance'
    | '/student-attendance'
    | '/timetable'
    | '/today-attendance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/performance'
    | '/student-attendance'
    | '/timetable'
    | '/today-attendance'
  id:
    | '__root__'
    | '/'
    | '/performance'
    | '/student-attendance'
    | '/timetable'
    | '/today-attendance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerformanceRoute: typeof PerformanceRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  TimetableRoute: typeof TimetableRoute
  TodayAttendanceRoute: typeof TodayAttendanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-attendance': {
      id: '/student-attendance'
      path: '/student-attendance'
      fullPath: '/student-attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today-attendance': {
      id: '/today-attendance'
      path: '/today-attendance'
      fullPath: '/today-attendance'
      preLoaderRoute: typeof TodayAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerformanceRoute: PerformanceRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  TimetableRoute: TimetableRoute,
  TodayAttendanceRoute: TodayAttendanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
